// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6DqttOYBcKTvK4w_BTQftH-BOjyek_as',
    appId: '1:188166314767:web:399d82f762df60ac02fc7a',
    messagingSenderId: '188166314767',
    projectId: 'websitealpha',
    authDomain: 'websitealpha.firebaseapp.com',
    storageBucket: 'websitealpha.firebasestorage.app',
    measurementId: 'G-YS71FQW9NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_l9Fdd6PY1CD5rBPtOpbk42_gSxqp4e0',
    appId: '1:188166314767:android:0f302183b3fd57bf02fc7a',
    messagingSenderId: '188166314767',
    projectId: 'websitealpha',
    storageBucket: 'websitealpha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIPfxsWDmRy0lmXTPYYNfg180uLDtzoko',
    appId: '1:188166314767:ios:44b19d92cf96053802fc7a',
    messagingSenderId: '188166314767',
    projectId: 'websitealpha',
    storageBucket: 'websitealpha.firebasestorage.app',
    iosBundleId: 'com.example.geminicliApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIPfxsWDmRy0lmXTPYYNfg180uLDtzoko',
    appId: '1:188166314767:ios:44b19d92cf96053802fc7a',
    messagingSenderId: '188166314767',
    projectId: 'websitealpha',
    storageBucket: 'websitealpha.firebasestorage.app',
    iosBundleId: 'com.example.geminicliApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6DqttOYBcKTvK4w_BTQftH-BOjyek_as',
    appId: '1:188166314767:web:4a02848840efd29702fc7a',
    messagingSenderId: '188166314767',
    projectId: 'websitealpha',
    authDomain: 'websitealpha.firebaseapp.com',
    storageBucket: 'websitealpha.firebasestorage.app',
    measurementId: 'G-D9VFCB0BDS',
  );
}
