import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'theme/app_theme.dart';
import 'package:firebase_core/firebase_core.dart'; // 1. Add this
import 'firebase_options.dart'; // 2. Add this (generated by CLI)
import 'router.dart';

void main() async {
  // 3. Ensure engine is ready for platform calls
  WidgetsFlutterBinding.ensureInitialized();

  // 4. Initialize Firebase with the specific Web App credentials
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const ProviderScope(child: MyApp()));
}

class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp.router(
      title: 'SOC Foundry',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.darkTheme,
      routerConfig: router,
    );
  }
}